### ISSUE TITLE
make jon a contributor

### ISSUE THREAD

**Issue by brinerustle** [openawards/openawards#16]
we need to include jon as a contributor to the code.

**Comment by perepicornell** [comment]
Hi! Apaprently I don't have admin privileges for this repo, maybe @alfredgg can do it?

**Comment by alfredgg** [comment]
Nope! The owner of this repo is @brinerustle ... He is the one who can do it.

**Comment by brinerustle** [comment]
jejeje didn't realize you two were still getting notifications. sorry about that. I think you have to remove yourselves to stop getting notifications from the repo
